"""add et_his_contents paragraph_id foreign

Revision ID: 01072c1bc891
Revises: 93e61c5931ff
Create Date: 2025-03-07 15:00:37.016733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01072c1bc891'
down_revision: Union[str, None] = '93e61c5931ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'et_his_contents', 'et_paragraphs', ['paragraph_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'et_his_contents', type_='foreignkey')
    # ### end Alembic commands ###
