"""alert Task add taskType

Revision ID: 15a9a4dc9305
Revises: f9574457e1ba
Create Date: 2025-04-14 18:45:28.141650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15a9a4dc9305'
down_revision: Union[str, None] = 'f9574457e1ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('et_tasks', sa.Column('task_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('et_tasks', 'task_type')
    # ### end Alembic commands ###
