"""Initial migration

Revision ID: 2d5d21d24f91
Revises: 
Create Date: 2025-03-05 14:45:00.866724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d5d21d24f91'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('et_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('author', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('create_dt', sa.DateTime(), nullable=True),
    sa.Column('modify_dt', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('et_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('create_dt', sa.DateTime(), nullable=True),
    sa.Column('modify_dt', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['et_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('et_paragraphs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('paragraph_type', sa.String(length=15), nullable=True),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('create_dt', sa.DateTime(), nullable=True),
    sa.Column('modify_dt', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['et_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('et_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blockno', sa.String(length=50), nullable=True),
    sa.Column('fileno', sa.String(length=50), nullable=True),
    sa.Column('paragraph_id', sa.Integer(), nullable=True),
    sa.Column('create_dt', sa.DateTime(), nullable=True),
    sa.Column('modify_dt', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['paragraph_id'], ['et_paragraphs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paragraph_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('et_contents')
    op.drop_table('et_paragraphs')
    op.drop_table('et_pages')
    op.drop_table('et_documents')
    # ### end Alembic commands ###
