"""alert Task add snapshot_id

Revision ID: 392dc56b32af
Revises: 937d7164bb44
Create Date: 2025-04-15 17:54:22.458009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '392dc56b32af'
down_revision: Union[str, None] = '937d7164bb44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('et_tasks', sa.Column('snapshot_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('et_tasks', 'snapshot_id')
    # ### end Alembic commands ###
