"""alert Task add comment, prev_id, next_id

Revision ID: 4e8624aba1b4
Revises: 392dc56b32af
Create Date: 2025-04-16 14:37:58.474103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e8624aba1b4'
down_revision: Union[str, None] = '392dc56b32af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('et_tasks', sa.Column('create_by', sa.Integer(), nullable=True))
    op.add_column('et_tasks', sa.Column('comment', sa.String(length=500), nullable=True))
    op.add_column('et_tasks', sa.Column('prev_id', sa.Integer(), nullable=True))
    op.add_column('et_tasks', sa.Column('next_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('et_tasks', 'next_id')
    op.drop_column('et_tasks', 'prev_id')
    op.drop_column('et_tasks', 'comment')
    op.drop_column('et_tasks', 'create_by')
    # ### end Alembic commands ###
