"""alert Task add business_status, description

Revision ID: 7a98b052030c
Revises: 4e8624aba1b4
Create Date: 2025-04-21 10:05:02.453886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a98b052030c'
down_revision: Union[str, None] = '4e8624aba1b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('et_tasks', sa.Column('business_status', sa.Integer(), nullable=True))
    op.add_column('et_tasks', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('et_tasks', 'description')
    op.drop_column('et_tasks', 'business_status')
    # ### end Alembic commands ###
