"""initial label data

Revision ID: 7d78d8f88cc8
Revises: 6dfcad4824d6
Create Date: 2025-03-13 16:16:12.240346

"""
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d78d8f88cc8'
down_revision: Union[str, None] = '6dfcad4824d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    metadata = sa.MetaData()
    metadata.reflect(bind=op.get_bind())

    categories_data = [
        {"name": "EDC", "create_dt": datetime.now(timezone.utc), "modify_dt": datetime.now(timezone.utc), "is_delete": 0 },
        {"name": "CRF DESIGN", "create_dt": datetime.now(timezone.utc), "modify_dt": datetime.now(timezone.utc), "is_delete": 0},
        {"name": "PV", "create_dt": datetime.now(timezone.utc), "modify_dt": datetime.now(timezone.utc), "is_delete": 0},
        {"name": "CTMS", "create_dt": datetime.now(timezone.utc), "modify_dt": datetime.now(timezone.utc), "is_delete": 0},
        {"name": "eTMF", "create_dt": datetime.now(timezone.utc), "modify_dt": datetime.now(timezone.utc), "is_delete": 0},
        {"name": "ADMIN", "create_dt": datetime.now(timezone.utc), "modify_dt": datetime.now(timezone.utc), "is_delete": 0},
        {"name": "CMD", "create_dt": datetime.now(timezone.utc), "modify_dt": datetime.now(timezone.utc), "is_delete": 0},
        {"name": "ProCheck", "create_dt": datetime.now(timezone.utc), "modify_dt": datetime.now(timezone.utc), "is_delete": 0},
        {"name": "Medical Coding", "create_dt": datetime.now(timezone.utc), "modify_dt": datetime.now(timezone.utc), "is_delete": 0},
        {"name": "Medical Image", "create_dt": datetime.now(timezone.utc), "modify_dt": datetime.now(timezone.utc), "is_delete": 0},
        {"name": "IRC", "create_dt": datetime.now(timezone.utc), "modify_dt": datetime.now(timezone.utc), "is_delete": 0},
        {"name": "其它", "create_dt": datetime.now(timezone.utc), "modify_dt": datetime.now(timezone.utc), "is_delete": 0},
    ]
    table = metadata.tables["et_label_categories"]
    # 使用 bulk_insert 插入数据
    op.bulk_insert(
        table,  # 表名
        rows=categories_data,  # 要插入的数据（字典列表）
    )
    # lab_data = [
    #     {"name": "audit trail", "category": "EDC", "create_dt": datetime.now(timezone.utc), "modify_dt": datetime.now(timezone.utc), "is_delete": 0},
    #     {"name": "sdv", "category": "EDC", "create_dt": datetime.now(timezone.utc), "modify_dt": datetime.now(timezone.utc), "is_delete": 0},
    #     {"name": "elearning", "category": "ADMIN", "create_dt": datetime.now(timezone.utc), "modify_dt": datetime.now(timezone.utc), "is_delete": 0},
    #     {"name": "folder", "category": "CMD", "create_dt": datetime.now(timezone.utc), "modify_dt": datetime.now(timezone.utc), "is_delete": 0},
    #     {"name": "unique form", "category": "CRF DESIGN", "create_dt": datetime.now(timezone.utc), "modify_dt": datetime.now(timezone.utc), "is_delete": 0},
    #     {"name": "edit check", "category": "CRF DESIGN", "create_dt": datetime.now(timezone.utc), "modify_dt": datetime.now(timezone.utc), "is_delete": 0},
    #     {"name": "populated", "category": "CRF DESIGN", "create_dt": datetime.now(timezone.utc), "modify_dt": datetime.now(timezone.utc), "is_delete": 0},
    #     {"name": "monitoring action items", "category": "CRF DESIGN", "create_dt": datetime.now(timezone.utc), "modify_dt": datetime.now(timezone.utc), "is_delete": 0},
    #     {"name": "site", "category": "CTMS", "create_dt": datetime.now(timezone.utc), "modify_dt": datetime.now(timezone.utc), "is_delete": 0},
    #     {"name": "automation event", "category": "CTMS", "create_dt": datetime.now(timezone.utc), "modify_dt": datetime.now(timezone.utc), "is_delete": 0},
    #     {"name": "stdm", "category": "ProCheck", "create_dt": datetime.now(timezone.utc), "modify_dt": datetime.now(timezone.utc), "is_delete": 0},
    # ]
    # table = metadata.tables["et_labels"]
    # op.bulk_insert(
    #     table, # 表名
    #     rows=lab_data,  # 要插入的数据（字典列表）
    # )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM et_labels")
    op.execute("DELETE FROM et_label_categories")
    # ### end Alembic commands ###
