"""alert Task add document_id

Revision ID: 937d7164bb44
Revises: 15a9a4dc9305
Create Date: 2025-04-15 10:37:39.541166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '937d7164bb44'
down_revision: Union[str, None] = '15a9a4dc9305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('et_tasks', sa.Column('document_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'et_tasks', 'et_documents', ['document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'et_tasks', type_='foreignkey')
    op.drop_column('et_tasks', 'document_id')
    # ### end Alembic commands ###
