"""remove et_his_contents paragraph_id uniqe

Revision ID: 93e61c5931ff
Revises: c83436eba7c9
Create Date: 2025-03-07 14:51:08.213723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93e61c5931ff'
down_revision: Union[str, None] = 'c83436eba7c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('et_his_contents_ibfk_1', 'et_his_contents', type_='foreignkey')
    op.drop_index('paragraph_id', table_name='et_his_contents')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('paragraph_id', 'et_his_contents', ['paragraph_id'], unique=True)
    # ### end Alembic commands ###
