"""alter et_snapshot_documents add name

Revision ID: adb2228ccf97
Revises: f8d6c7255eb8
Create Date: 2025-03-27 14:21:21.608917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adb2228ccf97'
down_revision: Union[str, None] = 'f8d6c7255eb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('et_snapshot_documents', sa.Column('name', sa.String(length=70), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('et_snapshot_documents', 'name')
    # ### end Alembic commands ###
