"""remove et_contents and et_paragraph add fileno and blockno

Revision ID: c83436eba7c9
Revises: f8997299b2a0
Create Date: 2025-03-07 13:23:26.016347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c83436eba7c9'
down_revision: Union[str, None] = 'f8997299b2a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('et_contents_ibfk_1', 'et_contents', type_='foreignkey')
    op.drop_index('paragraph_id', table_name='et_contents')
    op.drop_table('et_contents')
    op.add_column('et_paragraphs', sa.Column('blockno', sa.String(length=50), nullable=True))
    op.add_column('et_paragraphs', sa.Column('fileno', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('et_paragraphs', 'fileno')
    op.drop_column('et_paragraphs', 'blockno')
    op.create_table('et_contents',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('blockno', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('fileno', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('paragraph_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('create_dt', mysql.DATETIME(), nullable=True),
    sa.Column('modify_dt', mysql.DATETIME(), nullable=True),
    sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['paragraph_id'], ['et_paragraphs.id'], name='et_contents_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('paragraph_id', 'et_contents', ['paragraph_id'], unique=True)
    # ### end Alembic commands ###
