"""alter LabelCategory add category_type

Revision ID: d1fb6a9772ae
Revises: 5bfb01a5550c
Create Date: 2025-04-11 14:07:37.866345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1fb6a9772ae'
down_revision: Union[str, None] = '5bfb01a5550c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('et_label_categories', sa.Column('category_type', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('et_label_categories', 'category_type')
    # ### end Alembic commands ###
