"""ADD et_his_contents

Revision ID: f8997299b2a0
Revises: 2d5d21d24f91
Create Date: 2025-03-05 18:08:04.244433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8997299b2a0'
down_revision: Union[str, None] = '2d5d21d24f91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('et_his_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blockno', sa.String(length=50), nullable=True),
    sa.Column('fileno', sa.String(length=50), nullable=True),
    sa.Column('paragraph_id', sa.Integer(), nullable=True),
    sa.Column('create_dt', sa.DateTime(), nullable=True),
    sa.Column('modify_dt', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['paragraph_id'], ['et_paragraphs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paragraph_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('et_his_contents')
    # ### end Alembic commands ###
