"""add snapshot

Revision ID: f8d6c7255eb8
Revises: 0733efc12fb0
Create Date: 2025-03-27 09:43:26.948083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8d6c7255eb8'
down_revision: Union[str, None] = '0733efc12fb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('et_snapshot_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('labels', sa.String(length=1000), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('create_dt', sa.DateTime(), nullable=True),
    sa.Column('modify_dt', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['et_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('et_snapshot_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_document_id', sa.Integer(), nullable=True),
    sa.Column('page_name', sa.String(length=100), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('create_dt', sa.DateTime(), nullable=True),
    sa.Column('modify_dt', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_document_id'], ['et_snapshot_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('et_snapshot_paragraphs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_page_id', sa.Integer(), nullable=True),
    sa.Column('blockno', sa.String(length=50), nullable=True),
    sa.Column('fileno', sa.String(length=50), nullable=True),
    sa.Column('create_dt', sa.DateTime(), nullable=True),
    sa.Column('modify_dt', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_page_id'], ['et_snapshot_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('et_snapshot_paragraphs')
    op.drop_table('et_snapshot_pages')
    op.drop_table('et_snapshot_documents')
    # ### end Alembic commands ###
