"""add Task TaskAssignee DocumentAudit

Revision ID: f9574457e1ba
Revises: d1fb6a9772ae
Create Date: 2025-04-14 18:28:22.684762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9574457e1ba'
down_revision: Union[str, None] = 'd1fb6a9772ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('et_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('create_dt', sa.DateTime(), nullable=True),
    sa.Column('modify_dt', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('et_document_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('when', sa.DateTime(), nullable=True),
    sa.Column('who', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('action_object', sa.String(length=100), nullable=True),
    sa.Column('prepositions', sa.String(length=10), nullable=True),
    sa.Column('action_target', sa.String(length=100), nullable=True),
    sa.Column('create_dt', sa.DateTime(), nullable=True),
    sa.Column('modify_dt', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['et_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('et_task_assignees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('create_dt', sa.DateTime(), nullable=True),
    sa.Column('modify_dt', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['et_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('et_task_assignees')
    op.drop_table('et_document_audits')
    op.drop_table('et_tasks')
    # ### end Alembic commands ###
